name: release

on:
  push:
    branches: ["main"] # master 分支提交时触发

jobs:
  build:
    runs-on: ubuntu-latest # 运行环境
    steps:
      - name: checkout
        uses: actions/checkout@main
      - name: setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: 安装依赖
        run: npm install
      - name: 前端项目打包
        run: npm run build
      - name: 发布腾讯云
        uses: wlixcc/SFTP-Deploy-Action@v1.0 # 使用 SFTP 协议上传到腾讯云
        with:
          username: 'root'
          server: '${{ secrets.TENCENT_SERVER_HOST }}'
          ssh_private_key: '${{ secrets.TENCENT_SERVER_PRIVATE_KEY }}'
          local_path: './dist/*'
          remote_path: '/root/test-cd-docker'
          args: "-o ConnectTimeout=5"
