name: release

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest # 运行环境
    steps:
      - name: checkout
        uses: actions/checkout@main

      - name: setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"

      - name: 安装依赖
        run: 'npm install'

      - name: 前端项目打包
        run: npm run build

      
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete --exclude="" --include="" --filter=""
          path: ./test-cd-docker_${{ steps.vars.outputs.short_ref }}.tar
          remote_path: /www/test-cd-docker
          remote_host: ${{ secrets.TENCENT_SERVER_HOST }}
          remote_port: 22
          remote_user: root
          remote_key: ${{ secrets.TENCENT_SERVER_PRIVATE_KEY }}
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 获取分支号
        id: 'vars'
        run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}

      - name: 构建&上传镜像
        run: | 
          echo "准备构建镜像：test-cd-docker:${{ steps.vars.outputs.short_ref }}"
          sudo docker login --username=${{ secrets.ALI_DOCKERHUB_ACCOUNT }} --password=${{ secrets.ALI_DOCKERHUB_PASSWORD }} registry.cn-guangzhou.aliyuncs.com
          docker version
          docker build -f Dockerfile -t registry.cn-guangzhou.aliyuncs.com/yb_registry/test-cd-docker:${{ steps.vars.outputs.short_ref }} .
          docker push registry.cn-guangzhou.aliyuncs.com/yb_registry/test-cd-docker:${{ steps.vars.outputs.short_ref }}