name: release

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest # 运行环境
    steps:
      - name: checkout
        uses: actions/checkout@main
      - name: setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      - name: 安装依赖
        run: npm install
      - name: 前端项目打包
        run: npm run build
      - name: 创建远程目录
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TENCENT_SERVER_HOST }}
          username: root
          key: ${{ secrets.TENCENT_SERVER_PRIVATE_KEY }}
          port: 22
          script: 'cd /www/ && ./mkdir.sh test-cd-docker'
      - name: 发布腾讯云
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete --exclude="" --include="" --filter=""
          path: ./dist
          remote_path: /www/test-cd-docker
          remote_host: ${{ secrets.TENCENT_SERVER_HOST }}
          remote_port: 22
          remote_user: root
          remote_key: ${{ secrets.TENCENT_SERVER_PRIVATE_KEY }}
