name: release

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest # 运行环境
    steps:
      - name: checkout
        uses: actions/checkout@main

      - name: setup nodejs
        uses: actions/setup-node@v2
        with:
          node-version: "16.x"
      
      - name: 查看上下文
        run: ls
